FROM mcr.microsoft.com/devcontainers/base:bullseye

# تثبيت تبعيات Tauri
RUN apt-get update && \
    apt-get install -y libgtk-3-0 libwebkit2gtk-4.0-dev \
    libssl-dev libappindicator3-dev librsvg2-dev patchelf
